# This is a basic workflow to help you get started with Actions
name: CICD - Dev
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: ./node_modules/.bin/vite build
      - name: Copy files to the target S3 bucket
        run: aws s3 sync dist s3://mysba-portal-frontend-dev