# This is a basic workflow to help you get started with Actions
name: Dev Portal Frontend Build & Deploy

on:
  push:
    branches: [ "dev" ]

# sets the default shell for all jobs
defaults:
  run:
    shell: bash

# permissions can be set globally for jobs
permissions:
  contents: read # contents is used for checking out code
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ./node_modules/.bin/vite build --mode dev
        env:
          # Load .env.dev file
          NODE_ENV: dev

      - name: Copy files to the target S3 bucket
        run: aws s3 sync dist s3://474340895216-us-east-1-dev-mysba-portal-frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: 'Install Terraform 1.6.1'
        uses: 'hashicorp/setup-terraform@v3'
        with:
          terraform_version: '1.6.1'

      - name: Terraform Plan & Apply
        uses: ./.github/actions/terraform
        with:
          folder: ./terraform
          workspace: dev
