# This is a basic workflow to help you get started with Actions
name: Stg Portal Frontend Build & Deploy
on:
  push:
    branches: [ "stg" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ./node_modules/.bin/vite build

      - name: Copy files to the target S3 bucket
        run: aws s3 sync dist s3://mysba-portal-frontend-stg

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: 'Install Terraform 1.6.1'
        uses: 'hashicorp/setup-terraform@v2'
        with:
          terraform_version: '1.6.1'

      - name: Terraform Plan & Apply
        uses: ./.github/actions/terraform
        with:
          folder: ./terraform
          workspace: stg
